### PR TITLE
Add info on how to send autodiscovery information for Home Assistant MQTT sensors

### PR DESCRIPTION
**Pull request by danielszilagyi**
Hello,

I have found your project while suffering on [an ongoing issue with the Home Assistant We Connect integration](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/493) which impacts apparently more than just a few people. Since I am using automations for i.e. using solar energy to charge and announcements of range and SoC for an EV, I have implemented a few MQTT sensors that pull data sent to the broker by your software.

I thought these lines could be some of a help for those who just want a recovery quickly for the missing sensors while the issue gets fixed.

### CODE REVIEW

**Comment by tillsteinbach** [comment]
I would prefer this to go to the Wiki

**Comment by danielszilagyi** [comment]
Added in the [Wiki](https://github.com/tillsteinbach/WeConnect-mqtt/wiki/Autodiscovery-commands-for-Home-Assistant-weconnect-mqtt-sensors)

**Comment by tillsteinbach** [comment]
Great! Thank you for contributing!

**Comment by andreasd** [comment]
Hi!

I added another page to the wiki: https://github.com/tillsteinbach/WeConnect-mqtt/wiki/Home-assistant-sensors

This creates the sensors directly in home assistant which might be a bit easier for many people. Although best case would be if the sensors are auto generated, this at least allows for easy customization in the home assistant frontend.

**Pull request closed without merging**
